version: '3.9'
services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: appdb
    ports: ["5432:5432"]
    healthcheck:
      test: ["CMD-SHELL","pg_isready -U postgres"]
      interval: 5s
      timeout: 3s
      retries: 20
    volumes:
      - ./db-init:/docker-entrypoint-initdb.d
  app:
    build: ./app
    environment:
      PORT: 3000
      POSTGRES_URL: postgres://postgres:postgres@db:5432/appdb
    ports: ["3000:3000"]
    depends_on:
      db:
        condition: service_healthy
