import { strict as assert } from 'assert';
import { LRU } from '../src/index.js';
const lru=new LRU(2);
lru.put(1,1); lru.put(2,2);
assert.equal(lru.get(1),1);
lru.put(3,3);
assert.equal(lru.get(2),-1);
lru.put(4,4);
assert.equal(lru.get(1),-1);
assert.equal(lru.get(3),3);
assert.equal(lru.get(4),4);
console.log('PB-10 OK');
